"""empty message

Revision ID: 3a76324b1110
Revises: 952573841552
Create Date: 2023-03-07 14:04:25.369614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a76324b1110'
down_revision = '952573841552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('headsup_channel', sa.String(length=50), nullable=False))
        batch_op.drop_column('headsup_chanel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headsup_chanel', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('headsup_channel')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
