"""empty message

Revision ID: 952573841552
Revises: 10b79148e00d
Create Date: 2023-03-07 13:01:56.209318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '952573841552'
down_revision = '10b79148e00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('employement_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('daily_plan_channel', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('headsup_chanel', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['slack_id'])
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('headsup_chanel')
        batch_op.drop_column('daily_plan_channel')
        batch_op.drop_column('employement_status')
        batch_op.drop_column('role')
        batch_op.drop_column('slack_id')

    # ### end Alembic commands ###
