"""empty message

Revision ID: aa26d9de6f0b
Revises: a836319dddcc
Create Date: 2023-03-09 15:59:29.551289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa26d9de6f0b'
down_revision = 'a836319dddcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('slack_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=250), nullable=False),
    sa.Column('employement_status', sa.String(length=50), nullable=False),
    sa.Column('daily_plan_channel', sa.String(length=50), nullable=False),
    sa.Column('headsup_channel', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('slack_id'),
    sa.UniqueConstraint('slack_id')
    )
    op.create_table('time_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('slack_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['slack_id'], ['user.slack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_sheet')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
